language: ruby
rvm:
  - 2.3.1
sudo: required

before_script:
  - bundle exec rake db:setup

script:
  - bundle exec rspec

addons:
  code_climate:
    repo_token: bffbb5d80342055b6a7bbcba569bbf777d6354ee967c7063f355b5823833a0b3
