common: &common
  email: Rails.application.secrets.cloudflare_email
  api_key: Rails.application.secrets.cloudflare_api_key
  test_app_url: Rails.application.secrets.test_app_url
  test_domain: Rails.application.secrets.test_domain
  test_forward_url: Rails.application.secrets.test_forward_url
  test_rule_id: Rails.application.secrets.test_rule_id
  test_zone_id: Rails.application.secrets.test_zone_id;p

<%= Rails.env %>:
  <<: *common
