default: &default
  adapter: mysql2
  database: api
  host: <%= ENV['DATABASE_PORT_3306_TCP_ADDR'] %>
  port: <%= ENV['DATABASE_PORT_3306_TCP_PORT'] %>
  username: api-user
  password: mypassword

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
