common: &common
  rightscale-email: Rails.application.secrets.rightscale_email
  rightscale-password: Rails.application.secrets.rightscale_password
  accounts:
    -
      name: 'account name'
      id: 'account id'

<%= Rails.env %>:
  <<: *common
