---
- name: Provision Devops Control API
  hosts: all
  become: yes

  tasks:
    - name: set up docker permissions
      become: yes
      command: '{{ item }}'
      with_items:
        - "usermod -aG docker vagrant"

    - name: turn on docker
      service: name=docker state=started

    - name: fix sudoers file
      become: yes
      command: '{{ item }}'
      with_items:
        - 'touch /etc/sudoers'
        - 'cat <<EOF > /etc/sudoers
          Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
          Cmnd_Alias VAGRANT_NFSD_CHECK = /usr/bin/systemctl status --no-pager nfs-server.service
          Cmnd_Alias VAGRANT_NFSD_START = /usr/bin/systemctl start nfs-server.service
          Cmnd_Alias VAGRANT_NFSD_APPLY = /usr/sbin/exportfs -ar
          Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /bin/sed -r -e * d -ibak /tmp/exports
          %vagrant ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD_CHECK, VAGRANT_NFSD_START, VAGRANT_NFSD_APPLY, VAGRANT_EXPORTS_REMOVE
          EOF'
